<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Alternar navegação</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">CRM</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="active">
                <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), 'lista', true); ?>">
                    <i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;Início
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'clientes', 'action' => 'index'), 'lista', true); ?>">
                    <i class="glyphicon-regular glyphicon-briefcase"></i>&nbsp;&nbsp;Clientes
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'atendimentos', 'action' => 'index'), 'lista', true); ?>">
                    <i class="glyphicon glyphicon-earphone"></i>&nbsp;&nbsp;Atendimentos
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'relatorios', 'action' => 'index'), 'lista', true); ?>">
                    <i class="glyphicon-regular glyphicon-pie_chart"></i>&nbsp;&nbsp;Relatórios
                </a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="glyphicon-regular glyphicon-settings"></i>
                    &nbsp;&nbsp;Configurações <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'usuarios', 'action' => 'index'), 'lista', true); ?>">
                            <i class="glyphicon-regular glyphicon-user"></i>&nbsp;&nbsp;Usuários
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'grupos', 'action' => 'index'), 'lista', true); ?>">
                            <i class="glyphicon-regular glyphicon-group"></i>&nbsp;&nbsp;Grupos
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'menus', 'action' => 'index'), 'lista', true); ?>">
                            <i class="glyphicon-halflings glyphicon-link"></i>&nbsp;&nbsp;Menus
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right" style="margin-right: 0;">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="glyphicon glyphicon-user"></i>&nbsp;
                    William Urbano <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">Logout</a></li>
                </ul>
            </li>
        </ul>
    </div>
    </div>
</nav>