<fieldset>
    <legend>Usuarios</legend>

    <form class="form-horizontal" role="form">
        <div class="form-group">
            <label for="usuarios_razão_social" class="col-sm-2 control-label">Empresa</label>
            <div class="col-sm-10">
                <select name="usuario_empresa" id="usuario_empresa" class="form-control">
                    <option>Selecione a empresa</option>
                </select>
            </div>
        </div>
        
        <div class="form-group">
            <label for="usuario_nome" class="col-sm-2 control-label">Nome</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="usuario_nome" name="usuario_nome" placeholder="Nome do usuario">
            </div>
        </div>

        <div class="form-group">
            <label for="usuario_email" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="usuario_email" name="usuario_email" placeholder="Email de acesso">
            </div>
        </div>

        <div class="form-group">
            <label for="usuario_email" class="col-sm-2 control-label">
                Senha
            </label>
            <div class="col-sm-5">
                <input type="password" class="form-control" id="usuario_senha" name="usuario_senha" placeholder="Senha de acesso">
            </div>
            <div class="col-sm-5">
                <input type="password" class="form-control" id="usuario_senha" name="usuario_senha" placeholder="Confirme a senha de acesso">
            </div>
        </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success"><span class="glyphicon-regular glyphicon-ok_2"></span>&nbsp;&nbsp;&nbsp;Salvar</button>
                        <a href="<?php echo $this->url(array('controller' => 'clientes', 'action' => 'index'), 'lista'); ?>" class="btn btn-danger">
                            <span class="glyphicon-halflings glyphicon-remove"></span>&nbsp;&nbsp;&nbsp;Cancelar
                        </a>
                    </div>
                </div>
    </form>
</fieldset>