<?php echo $this->doctype() . PHP_EOL; ?>
<html>
<head>
    <?php echo $this->headTitle() . PHP_EOL; ?>
    <?php echo $this->headMeta() . PHP_EOL; ?>
    <base href="<?php echo $this->baseUrl('/'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/extends.css" rel="stylesheet">
    <link href="assets/css/yeti.min.css" rel="stylesheet">
    <link href="assets/css/crm.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <?php echo $this->partial('partials/nav.phtml'); ?>

    <div class="container">
        <?php echo $this->layout()->content; ?>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="assets/js/jquery-2.0.3.min.js"></script>
    <script src="assets/js/jquery-migrate-1.2.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="assets/js/bootstrap.min.js"></script>
</body>
</html>