<fieldset>
    <legend>Clientes</legend>

    <form class="form-horizontal" role="form">
        <div class="form-group">
            <label for="cliente_razao_social" class="col-sm-2 control-label">Razão social</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="cliente_razao_social" name="cliente_razao_social" placeholder="Razão social">
            </div>
        </div>
        
        <div class="form-group">
            <label for="cliente_nome_fantasia" class="col-sm-2 control-label">Nome fantasia</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="cliente_nome_fantasia" name="cliente_nome_fantasia" placeholder="Nome fantasia">
            </div>
        </div>
        
        <div class="form-group">
            <label for="cliente_cnpj" class="col-sm-2 control-label">Documento</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="cliente_cnpj" name="cliente_cnpj" placeholder="CNPJ">
            </div>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="cliente_cpf" name="cliente_cpf" placeholder="CPF">
            </div>
        </div>


        <div class="form-group">
            <label for="cliente_endereco" class="col-sm-2 control-label">Endereço</label>
            <div class="col-sm-2">
                <select class="form-control">
                    <option>Selecione o estado</option>
                </select>
            </div>
            <div class="col-sm-4">
                <select class="form-control">
                    <option>Selecione a cidade</option>
                </select>
            </div>
            <div class="col-sm-4">
                <select class="form-control">
                    <option>Selecione o bairro</option>
                </select>
            </div>
        </div>

    </form>

</fieldset>